import {CertificateDownloadCheckList} from './CertificateDownloadCheckList';

export const actionTypes = {
  CERTIFICATE_DATA: 'CERTIFICATE_DATA',
  PROFILE_DATA: 'PROFILE_DATA',
  LOGIN_DATA: 'LOGIN_DATA',
  TICKETS_DATA: 'TICKETS_DATA',
  PARENT_STUDENT_DATA: 'PARENT_STUDENT_DATA',
  TEACHER_LIST: 'TEACHER_LIST',
  DESCIPLINE_LIST: 'DESCIPLINE_LIST',
  ANNOUNCEMENT_LIST: 'ANNOUNCEMENT_LIST',
  REPORT_LIST: 'REPORT_LIST',
  NOTIFICATION_API: 'NOTIFICATION_API',
};
