export const NAVIGATION_ROUTES = {
  INSPECTION_FORM: 'INSPECTION_FORM',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  LOGIN_SCREEN_ROUTE: 'LOGIN_SCREEN_ROUTE',
  HOME: 'HOME',
  MENU: 'MENU',
  DRAWER: 'DRAWER',
  TICKET_DETAIL: 'TICKET_DETAIL',
  DESCIPLINE_DETAIL: 'DESCIPLINE_DETAIL',
  ANNOUNCEMENT_DETAIL: 'ANNOUNCEMENT_DETAIL',
  REPORT_DETAIL: 'REPORT_DETAIL',
};
